/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    categories: Category;
    services: Service;
    blogPosts: BlogPost;
    projects: Project;
    testimonials: Testimonial;
    faqs: Faq;
    contactSubmissions: ContactSubmission;
    pages: Page;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    blogPosts: BlogPostsSelect<false> | BlogPostsSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    contactSubmissions: ContactSubmissionsSelect<false> | ContactSubmissionsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    siteSettings: SiteSetting;
    navigation: Navigation;
    footer: Footer;
  };
  globalsSelect: {
    siteSettings: SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    username: string;
  };
  login: {
    password: string;
    username: string;
  };
  registerFirstUser: {
    password: string;
    username: string;
  };
  unlock: {
    username: string;
  };
}
/**
 * Kullanıcı hesaplarını yönetin.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  /**
   * Görünen ad.
   */
  name?: string | null;
  /**
   * Admin: Tam yetki | Editor: İçerik yönetimi
   */
  role?: ('admin' | 'editor') | null;
  updatedAt: string;
  createdAt: string;
  email?: string | null;
  username: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Görsel ve dosyaları yönetin.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    tablet?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Blog kategorilerini yönetin.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: string;
  name: string;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Hizmet sayfalarını yönetin.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: string;
  /**
   * URL adresi. Örn: sosyal-medya-yonetimi
   */
  slug: string;
  /**
   * Görünen ad.
   */
  title: string;
  /**
   * Başlık altındaki kısa açıklama.
   */
  subtitle: string;
  /**
   * Hizmet kartlarında görünen özet.
   */
  description: string;
  /**
   * Detay sayfasındaki uzun açıklama.
   */
  longDescription: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Hizmetin sunduğu ana özellikler.
   */
  features?:
    | {
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Hizmetin işleyiş adımları.
   */
  process?:
    | {
        step: number;
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  /**
   * SEO başlığı (max 60 karakter).
   */
  metaTitle: string;
  /**
   * SEO açıklaması (max 160 karakter).
   */
  metaDescription: string;
  /**
   * Hizmet kartı ikon görseli.
   */
  icon?: (string | null) | Media;
  /**
   * Hizmet sayfası ana rengi. Örn: #0040ff
   */
  accentColor: string;
  /**
   * Görünüm sırası. Küçük = önce.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Blog yazılarını yönetin.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blogPosts".
 */
export interface BlogPost {
  id: string;
  /**
   * Kapak görseli. 1200x630px önerilir.
   */
  featuredImage?: (string | null) | Media;
  /**
   * Yazının kategorisi.
   */
  category?: (string | null) | Category;
  /**
   * URL adresi. Örn: sosyal-medya-trendleri-2024
   */
  slug: string;
  /**
   * Yazının ana başlığı.
   */
  title: string;
  /**
   * Listeleme sayfasında görünen kısa özet.
   */
  excerpt: string;
  /**
   * Yazının ana içeriği.
   */
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Yayınlanma tarihi.
   */
  publishedDate: string;
  /**
   * Yazıyı yazan kişi.
   */
  author?: (string | null) | User;
  /**
   * SEO başlığı.
   */
  metaTitle?: string | null;
  /**
   * SEO açıklaması (max 160 karakter).
   */
  metaDescription?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Referans projeleri yönetin.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: string;
  /**
   * Görünüm sırası. Küçük = önce.
   */
  order?: number | null;
  /**
   * URL adresi. Örn: guzgun-tekstil
   */
  slug: string;
  /**
   * Projenin görünen adı.
   */
  title: string;
  /**
   * Proje kategorisi.
   */
  category: string;
  /**
   * Projede kullanılan hizmet etiketleri.
   */
  services?:
    | {
        label: string;
        slug: string;
        breakBefore?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Proje sonucu. Örn: Etkileşim +%2000
   */
  results: string;
  /**
   * Sonuç metni rengi.
   */
  resultsColor?: string | null;
  /**
   * Müşteri logosu.
   */
  logo?: (string | null) | Media;
  /**
   * Logo büyütme oranı.
   */
  logoScale?: number | null;
  /**
   * Etiketleri küçük boyutta göster.
   */
  smallTags?: boolean | null;
  /**
   * Arka plan gradient. Örn: from-emerald-500 to-teal-600
   */
  color: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Müşteri yorumlarını yönetin.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: string;
  /**
   * Profil fotoğrafı.
   */
  image?: (string | null) | Media;
  /**
   * Yıldız puanı.
   */
  rating?: number | null;
  /**
   * Görünüm sırası. Küçük = önce.
   */
  order?: number | null;
  /**
   * Müşteri adı soyadı.
   */
  name: string;
  /**
   * Firma adı.
   */
  company: string;
  /**
   * Ünvan. Örn: Genel Müdür
   */
  role?: string | null;
  /**
   * Müşteri deneyim yorumu.
   */
  text: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Sık sorulan soruları yönetin.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: string;
  /**
   * Görünüm sırası. Küçük = üstte.
   */
  order?: number | null;
  /**
   * Sık sorulan soru.
   */
  question: string;
  /**
   * Sorunun detaylı cevabı.
   */
  answer: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Gelen mesajları görüntüleyin.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contactSubmissions".
 */
export interface ContactSubmission {
  id: string;
  /**
   * Gönderenin adı ve soyadı.
   */
  name: string;
  /**
   * Geri dönüş e-posta adresi.
   */
  email: string;
  /**
   * Telefon numarası.
   */
  phone?: string | null;
  /**
   * İlgilenilen hizmetler.
   */
  service?: string | null;
  /**
   * Mesaj içeriği.
   */
  message: string;
  /**
   * Okundu olarak işaretle.
   */
  read?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Sayfaları yönetin. 'home' slug'ı ana sayfadır.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  /**
   * URL adresi. 'home' ana sayfayı temsil eder.
   */
  slug: string;
  /**
   * Panelde görünen sayfa adı.
   */
  title: string;
  /**
   * Sayfa blokları.
   */
  content?:
    | (
        | HeroBlock
        | MarqueeBlock
        | ServicesGridBlock
        | PortfolioSliderBlock
        | TestimonialsCarouselBlock
        | FaqAccordionBlock
        | AboutBlock
        | AiAutomationBlock
        | WhyUsBlock
        | PricingBlock
        | PartnerBadgesBlock
        | CtaBlock
      )[]
    | null;
  /**
   * SEO başlığı.
   */
  metaTitle?: string | null;
  /**
   * SEO açıklaması.
   */
  metaDescription?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock".
 */
export interface HeroBlock {
  icerik?: {
    /**
     * Sabit başlangıç metni
     */
    titlePrefix?: string | null;
    /**
     * Sırayla değişen kelimeler
     */
    animatedWords?:
      | {
          word: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Sabit bitiş metni
     */
    titleSuffix?: string | null;
    /**
     * Başlık altı açıklama
     */
    subtitle?: string | null;
  };
  cta?: {
    /**
     * Öne çıkan buton
     */
    primaryCta?: {
      text?: string | null;
      link?: string | null;
    };
    /**
     * İkinci buton
     */
    secondaryCta?: {
      text?: string | null;
      link?: string | null;
    };
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'hero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MarqueeBlock".
 */
export interface MarqueeBlock {
  /**
   * Kayan şeritteki logolar
   */
  items: {
    text: string;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'marquee';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ServicesGridBlock".
 */
export interface ServicesGridBlock {
  /**
   * Bölüm başlığı
   */
  sectionTitle?: string | null;
  /**
   * Tümünü otomatik getir
   */
  showAllServices?: boolean | null;
  /**
   * Manuel servis seçimi
   */
  selectedServices?: (string | Service)[] | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'servicesGrid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PortfolioSliderBlock".
 */
export interface PortfolioSliderBlock {
  /**
   * Bölüm başlığı
   */
  title: string;
  /**
   * Kısa açıklama
   */
  subtitle?: string | null;
  /**
   * Tümünü otomatik getir
   */
  showAllPortfolios?: boolean | null;
  /**
   * Manuel proje seçimi
   */
  selectedPortfolios?: (string | Project)[] | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'portfolioSlider';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialsCarouselBlock".
 */
export interface TestimonialsCarouselBlock {
  /**
   * Bölüm başlığı
   */
  title: string;
  /**
   * Tümünü otomatik getir
   */
  showAllTestimonials?: boolean | null;
  /**
   * Manuel referans seçimi
   */
  selectedTestimonials?: (string | Testimonial)[] | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'testimonialsCarousel';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FaqAccordionBlock".
 */
export interface FaqAccordionBlock {
  /**
   * Bölüm başlığı
   */
  title: string;
  /**
   * Kısa açıklama
   */
  subtitle?: string | null;
  /**
   * Tümünü otomatik getir
   */
  showAllFaqs?: boolean | null;
  /**
   * Manuel FAQ seçimi
   */
  selectedFaqs?: (string | Faq)[] | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'faqAccordion';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AboutBlock".
 */
export interface AboutBlock {
  /**
   * Bölüm başlığı
   */
  title: string;
  /**
   * Şirket açıklaması
   */
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Sayısal istatistikler
   */
  stats?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  image?: (string | null) | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'about';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AiAutomationBlock".
 */
export interface AiAutomationBlock {
  /**
   * Ana başlık
   */
  title?: string | null;
  /**
   * Kısa açıklama
   */
  subtitle?: string | null;
  /**
   * Detaylı içerik
   */
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Köşe etiketi
   */
  badge?: string | null;
  /**
   * Öne çıkan özellikler
   */
  features?:
    | {
        /**
         * Lucide ikon adı. Örn: Workflow, Bot, BarChart3, MessageSquare, Zap, BrainCircuit
         */
        icon?: string | null;
        label: string;
        desc: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'aiAutomation';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "WhyUsBlock".
 */
export interface WhyUsBlock {
  /**
   * Ana başlık
   */
  title?: string | null;
  /**
   * Kısa açıklama
   */
  subtitle?: string | null;
  /**
   * Neden biz? maddeleri
   */
  reasons?:
    | {
        /**
         * Lucide ikon adı. Örn: TrendingUp, Clock, Users, Award, Zap, CheckCircle2
         */
        icon?: string | null;
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'whyUs';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PricingBlock".
 */
export interface PricingBlock {
  /**
   * Bölüm başlığı
   */
  title?: string | null;
  /**
   * Kısa açıklama
   */
  subtitle?: string | null;
  /**
   * Fiyat paketleri
   */
  packages?:
    | {
        name: string;
        price: number;
        highlighted?: boolean | null;
        ctaText: string;
        ctaLink: string;
        features?:
          | {
              text: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'pricing';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PartnerBadgesBlock".
 */
export interface PartnerBadgesBlock {
  /**
   * Bölüm başlığı
   */
  title?: string | null;
  /**
   * Platform rozetleri
   */
  badges?:
    | {
        name: string;
        icon?: (string | null) | Media;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'partnerBadges';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CtaBlock".
 */
export interface CtaBlock {
  /**
   * Buton üstü başlık
   */
  title: string;
  /**
   * Kısa açıklama
   */
  subtitle?: string | null;
  /**
   * Buton üzerindeki metin
   */
  ctaText: string;
  /**
   * Yönlendirme linki
   */
  ctaLink: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: string | Category;
      } | null)
    | ({
        relationTo: 'services';
        value: string | Service;
      } | null)
    | ({
        relationTo: 'blogPosts';
        value: string | BlogPost;
      } | null)
    | ({
        relationTo: 'projects';
        value: string | Project;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: string | Testimonial;
      } | null)
    | ({
        relationTo: 'faqs';
        value: string | Faq;
      } | null)
    | ({
        relationTo: 'contactSubmissions';
        value: string | ContactSubmission;
      } | null)
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  username?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        tablet?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  subtitle?: T;
  description?: T;
  longDescription?: T;
  features?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  process?:
    | T
    | {
        step?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  metaTitle?: T;
  metaDescription?: T;
  icon?: T;
  accentColor?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blogPosts_select".
 */
export interface BlogPostsSelect<T extends boolean = true> {
  featuredImage?: T;
  category?: T;
  slug?: T;
  title?: T;
  excerpt?: T;
  content?: T;
  publishedDate?: T;
  author?: T;
  metaTitle?: T;
  metaDescription?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  order?: T;
  slug?: T;
  title?: T;
  category?: T;
  services?:
    | T
    | {
        label?: T;
        slug?: T;
        breakBefore?: T;
        id?: T;
      };
  results?: T;
  resultsColor?: T;
  logo?: T;
  logoScale?: T;
  smallTags?: T;
  color?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  image?: T;
  rating?: T;
  order?: T;
  name?: T;
  company?: T;
  role?: T;
  text?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  order?: T;
  question?: T;
  answer?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contactSubmissions_select".
 */
export interface ContactSubmissionsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  service?: T;
  message?: T;
  read?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  content?:
    | T
    | {
        hero?: T | HeroBlockSelect<T>;
        marquee?: T | MarqueeBlockSelect<T>;
        servicesGrid?: T | ServicesGridBlockSelect<T>;
        portfolioSlider?: T | PortfolioSliderBlockSelect<T>;
        testimonialsCarousel?: T | TestimonialsCarouselBlockSelect<T>;
        faqAccordion?: T | FaqAccordionBlockSelect<T>;
        about?: T | AboutBlockSelect<T>;
        aiAutomation?: T | AiAutomationBlockSelect<T>;
        whyUs?: T | WhyUsBlockSelect<T>;
        pricing?: T | PricingBlockSelect<T>;
        partnerBadges?: T | PartnerBadgesBlockSelect<T>;
        cta?: T | CtaBlockSelect<T>;
      };
  metaTitle?: T;
  metaDescription?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock_select".
 */
export interface HeroBlockSelect<T extends boolean = true> {
  icerik?:
    | T
    | {
        titlePrefix?: T;
        animatedWords?:
          | T
          | {
              word?: T;
              id?: T;
            };
        titleSuffix?: T;
        subtitle?: T;
      };
  cta?:
    | T
    | {
        primaryCta?:
          | T
          | {
              text?: T;
              link?: T;
            };
        secondaryCta?:
          | T
          | {
              text?: T;
              link?: T;
            };
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MarqueeBlock_select".
 */
export interface MarqueeBlockSelect<T extends boolean = true> {
  items?:
    | T
    | {
        text?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ServicesGridBlock_select".
 */
export interface ServicesGridBlockSelect<T extends boolean = true> {
  sectionTitle?: T;
  showAllServices?: T;
  selectedServices?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PortfolioSliderBlock_select".
 */
export interface PortfolioSliderBlockSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  showAllPortfolios?: T;
  selectedPortfolios?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialsCarouselBlock_select".
 */
export interface TestimonialsCarouselBlockSelect<T extends boolean = true> {
  title?: T;
  showAllTestimonials?: T;
  selectedTestimonials?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FaqAccordionBlock_select".
 */
export interface FaqAccordionBlockSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  showAllFaqs?: T;
  selectedFaqs?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AboutBlock_select".
 */
export interface AboutBlockSelect<T extends boolean = true> {
  title?: T;
  content?: T;
  stats?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  image?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AiAutomationBlock_select".
 */
export interface AiAutomationBlockSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  description?: T;
  badge?: T;
  features?:
    | T
    | {
        icon?: T;
        label?: T;
        desc?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "WhyUsBlock_select".
 */
export interface WhyUsBlockSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  reasons?:
    | T
    | {
        icon?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PricingBlock_select".
 */
export interface PricingBlockSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  packages?:
    | T
    | {
        name?: T;
        price?: T;
        highlighted?: T;
        ctaText?: T;
        ctaLink?: T;
        features?:
          | T
          | {
              text?: T;
              id?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PartnerBadgesBlock_select".
 */
export interface PartnerBadgesBlockSelect<T extends boolean = true> {
  title?: T;
  badges?:
    | T
    | {
        name?: T;
        icon?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CtaBlock_select".
 */
export interface CtaBlockSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  ctaText?: T;
  ctaLink?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Site adı, logo, SEO ve iletişim ayarları.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "siteSettings".
 */
export interface SiteSetting {
  id: string;
  siteName?: string | null;
  tagline?: string | null;
  /**
   * Şeffaf arka planlı PNG önerilir.
   */
  logo?: (string | null) | Media;
  /**
   * 32x32px veya 64x64px PNG.
   */
  favicon?: (string | null) | Media;
  contactEmail?: string | null;
  contactPhone?: string | null;
  /**
   * Sayfa başlığı yoksa kullanılır.
   */
  defaultMetaTitle?: string | null;
  /**
   * Sayfa açıklaması yoksa kullanılır.
   */
  defaultMetaDescription?: string | null;
  /**
   * Google Search Console doğrulama kodu.
   */
  googleVerification?: string | null;
  /**
   * Site renk şeması.
   */
  theme?: {
    primaryColor?: string | null;
    accentColor?: string | null;
    surfaceColor?: string | null;
    backgroundColor?: string | null;
    textColor?: string | null;
  };
  socialLinks?:
    | {
        platform: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Navbar menü linkleri ve CTA butonu.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: string;
  links?:
    | {
        label: string;
        href: string;
        isExternal?: boolean | null;
        order?: number | null;
        children?:
          | {
              label: string;
              href: string;
              isExternal?: boolean | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  ctaLabel?: string | null;
  ctaHref?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Footer CTA, linkler ve sosyal medya.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: string;
  /**
   * HTML etiketleri kullanabilirsiniz.
   */
  ctaTitle?: string | null;
  ctaSubtitle?: string | null;
  ctaButtonText?: string | null;
  /**
   * Footer link sütunları.
   */
  columns?:
    | {
        title: string;
        /**
         * Bu sütundaki linkler.
         */
        links?:
          | {
              label: string;
              href: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  bottomText?: string | null;
  brandTagline?: string | null;
  showNewsletter?: boolean | null;
  socialLinks?:
    | {
        platform: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "siteSettings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  tagline?: T;
  logo?: T;
  favicon?: T;
  contactEmail?: T;
  contactPhone?: T;
  defaultMetaTitle?: T;
  defaultMetaDescription?: T;
  googleVerification?: T;
  theme?:
    | T
    | {
        primaryColor?: T;
        accentColor?: T;
        surfaceColor?: T;
        backgroundColor?: T;
        textColor?: T;
      };
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  links?:
    | T
    | {
        label?: T;
        href?: T;
        isExternal?: T;
        order?: T;
        children?:
          | T
          | {
              label?: T;
              href?: T;
              isExternal?: T;
              id?: T;
            };
        id?: T;
      };
  ctaLabel?: T;
  ctaHref?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  ctaTitle?: T;
  ctaSubtitle?: T;
  ctaButtonText?: T;
  columns?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        id?: T;
      };
  bottomText?: T;
  brandTagline?: T;
  showNewsletter?: T;
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}